/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : UUID,
  'customerName' : string,
  'status' : BookingStatus,
  'paymentMethod' : PaymentMethod,
  'bookedBy' : Principal,
  'customerPhone' : string,
  'destinationId' : [] | [UUID],
  'createdAt' : Time,
  'numGuests' : bigint,
  'bookingDate' : Time,
  'totalPrice' : number,
  'customerEmail' : string,
  'packageId' : [] | [UUID],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export type ExternalBlob = Uint8Array;
export interface Hotel {
  'id' : UUID,
  'active' : boolean,
  'pricePerNight' : number,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'amenities' : Array<string>,
  'website' : string,
  'updatedAt' : Time,
  'address' : string,
  'rating' : bigint,
  'phone' : string,
}
export interface InputBooking {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'destinationId' : [] | [UUID],
  'numGuests' : bigint,
  'totalPrice' : number,
  'customerEmail' : string,
  'packageId' : [] | [UUID],
}
export interface InputHotel {
  'pricePerNight' : number,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'website' : string,
  'address' : string,
  'rating' : bigint,
  'phone' : string,
}
export interface InputTourAgency {
  'name' : string,
  'description' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
  'services' : Array<string>,
}
export interface InputTourDestination {
  'featured' : boolean,
  'directions' : string,
  'name' : string,
  'description' : string,
  'address' : string,
  'category' : string,
  'mainImage' : [] | [ExternalBlob],
  'coordinates' : Coordinates,
}
export interface InputTourPackage {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'inclusions' : Array<string>,
  'maxParticipants' : bigint,
  'price' : number,
}
export type PaymentMethod = { 'ovo' : null } |
  { 'linkAja' : null } |
  { 'dana' : null } |
  { 'gopay' : null };
export type Time = bigint;
export interface TourAgency {
  'id' : UUID,
  'active' : boolean,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'email' : string,
  'updatedAt' : Time,
  'address' : string,
  'phone' : string,
  'services' : Array<string>,
}
export interface TourDestination {
  'id' : UUID,
  'featured' : boolean,
  'active' : boolean,
  'directions' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'address' : string,
  'category' : string,
  'rating' : bigint,
  'mainImage' : [] | [ExternalBlob],
  'location' : Coordinates,
}
export interface TourPackage {
  'id' : UUID,
  'duration' : bigint,
  'active' : boolean,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'inclusions' : Array<string>,
  'updatedAt' : Time,
  'maxParticipants' : bigint,
  'price' : number,
}
export type UUID = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImages' : ActorMethod<[UUID, Array<ExternalBlob>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBookingClient' : ActorMethod<[UUID], undefined>,
  'checkBookingStatus' : ActorMethod<[UUID], BookingStatus>,
  'createAgency' : ActorMethod<[InputTourAgency], UUID>,
  'createBooking' : ActorMethod<[InputBooking], UUID>,
  'createDestination' : ActorMethod<[InputTourDestination], UUID>,
  'createHotel' : ActorMethod<[InputHotel], UUID>,
  'createTourPackage' : ActorMethod<[InputTourPackage], UUID>,
  'deleteAgency' : ActorMethod<[UUID], undefined>,
  'deleteDestination' : ActorMethod<[UUID], undefined>,
  'deleteHotel' : ActorMethod<[UUID], undefined>,
  'deleteTourPackage' : ActorMethod<[UUID], undefined>,
  'getActiveAgencies' : ActorMethod<[], Array<TourAgency>>,
  'getActiveDestinations' : ActorMethod<[], Array<TourDestination>>,
  'getActiveHotels' : ActorMethod<[], Array<Hotel>>,
  'getActiveTourPackages' : ActorMethod<[], Array<TourPackage>>,
  'getAgency' : ActorMethod<[UUID], TourAgency>,
  'getAllAgencies' : ActorMethod<[], Array<TourAgency>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllConfirmedBookings' : ActorMethod<[], Array<Booking>>,
  'getAllDestinations' : ActorMethod<[], Array<TourDestination>>,
  'getAllFeaturedWithGallery' : ActorMethod<
    [],
    Array<[TourDestination, Array<ExternalBlob>]>
  >,
  'getAllHotels' : ActorMethod<[], Array<Hotel>>,
  'getAllTourPackages' : ActorMethod<[], Array<TourPackage>>,
  'getBooking' : ActorMethod<[UUID], Booking>,
  'getBookingStats' : ActorMethod<
    [],
    {
      'pendingBookings' : bigint,
      'activeHotels' : bigint,
      'activePackages' : bigint,
      'cancelledBookings' : bigint,
      'totalBookings' : bigint,
      'confirmedBookings' : bigint,
      'activeDestinations' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDestination' : ActorMethod<[UUID], TourDestination>,
  'getDestinationGalleryImages' : ActorMethod<[UUID], Array<ExternalBlob>>,
  'getDestinationWithGallery' : ActorMethod<
    [UUID],
    [TourDestination, Array<ExternalBlob>]
  >,
  'getFeaturedDestinations' : ActorMethod<[], Array<TourDestination>>,
  'getGalleryImages' : ActorMethod<[UUID], Array<ExternalBlob>>,
  'getHomePageData' : ActorMethod<
    [],
    {
      'agencies' : Array<TourAgency>,
      'popularHotels' : Array<Hotel>,
      'tourPackages' : Array<TourPackage>,
      'featuredDestinations' : Array<TourDestination>,
    }
  >,
  'getHotel' : ActorMethod<[UUID], Hotel>,
  'getTourPackage' : ActorMethod<[UUID], TourPackage>,
  'getUserBookings' : ActorMethod<[string], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleAgencyActive' : ActorMethod<[UUID], undefined>,
  'toggleDestinationActive' : ActorMethod<[UUID], undefined>,
  'toggleHotelActive' : ActorMethod<[UUID], undefined>,
  'togglePackageActive' : ActorMethod<[UUID], undefined>,
  'updateAgency' : ActorMethod<[UUID, InputTourAgency], undefined>,
  'updateBookingStatusAdmin' : ActorMethod<[UUID, BookingStatus], undefined>,
  'updateDestination' : ActorMethod<[UUID, InputTourDestination], undefined>,
  'updateHotel' : ActorMethod<[UUID, InputHotel], undefined>,
  'updateTourPackage' : ActorMethod<[UUID, InputTourPackage], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];