/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UUID = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const InputTourAgency = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const PaymentMethod = IDL.Variant({
  'ovo' : IDL.Null,
  'linkAja' : IDL.Null,
  'dana' : IDL.Null,
  'gopay' : IDL.Null,
});
export const InputBooking = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'destinationId' : IDL.Opt(UUID),
  'numGuests' : IDL.Nat,
  'totalPrice' : IDL.Float64,
  'customerEmail' : IDL.Text,
  'packageId' : IDL.Opt(UUID),
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const InputTourDestination = IDL.Record({
  'featured' : IDL.Bool,
  'directions' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'mainImage' : IDL.Opt(ExternalBlob),
  'coordinates' : Coordinates,
});
export const InputHotel = IDL.Record({
  'pricePerNight' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'website' : IDL.Text,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const InputTourPackage = IDL.Record({
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'maxParticipants' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const TourAgency = IDL.Record({
  'id' : UUID,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const TourDestination = IDL.Record({
  'id' : UUID,
  'featured' : IDL.Bool,
  'active' : IDL.Bool,
  'directions' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'mainImage' : IDL.Opt(ExternalBlob),
  'location' : Coordinates,
});
export const Hotel = IDL.Record({
  'id' : UUID,
  'active' : IDL.Bool,
  'pricePerNight' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'website' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const TourPackage = IDL.Record({
  'id' : UUID,
  'duration' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
  'maxParticipants' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Booking = IDL.Record({
  'id' : UUID,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'paymentMethod' : PaymentMethod,
  'bookedBy' : IDL.Principal,
  'customerPhone' : IDL.Text,
  'destinationId' : IDL.Opt(UUID),
  'createdAt' : Time,
  'numGuests' : IDL.Nat,
  'bookingDate' : Time,
  'totalPrice' : IDL.Float64,
  'customerEmail' : IDL.Text,
  'packageId' : IDL.Opt(UUID),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImages' : IDL.Func([UUID, IDL.Vec(ExternalBlob)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBookingClient' : IDL.Func([UUID], [], []),
  'checkBookingStatus' : IDL.Func([UUID], [BookingStatus], ['query']),
  'createAgency' : IDL.Func([InputTourAgency], [UUID], []),
  'createBooking' : IDL.Func([InputBooking], [UUID], []),
  'createDestination' : IDL.Func([InputTourDestination], [UUID], []),
  'createHotel' : IDL.Func([InputHotel], [UUID], []),
  'createTourPackage' : IDL.Func([InputTourPackage], [UUID], []),
  'deleteAgency' : IDL.Func([UUID], [], []),
  'deleteDestination' : IDL.Func([UUID], [], []),
  'deleteHotel' : IDL.Func([UUID], [], []),
  'deleteTourPackage' : IDL.Func([UUID], [], []),
  'getActiveAgencies' : IDL.Func([], [IDL.Vec(TourAgency)], ['query']),
  'getActiveDestinations' : IDL.Func([], [IDL.Vec(TourDestination)], ['query']),
  'getActiveHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getActiveTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getAgency' : IDL.Func([UUID], [TourAgency], ['query']),
  'getAllAgencies' : IDL.Func([], [IDL.Vec(TourAgency)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllConfirmedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(TourDestination)], ['query']),
  'getAllFeaturedWithGallery' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TourDestination, IDL.Vec(ExternalBlob)))],
      ['query'],
    ),
  'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getBooking' : IDL.Func([UUID], [Booking], ['query']),
  'getBookingStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingBookings' : IDL.Nat,
          'activeHotels' : IDL.Nat,
          'activePackages' : IDL.Nat,
          'cancelledBookings' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'confirmedBookings' : IDL.Nat,
          'activeDestinations' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDestination' : IDL.Func([UUID], [TourDestination], ['query']),
  'getDestinationGalleryImages' : IDL.Func(
      [UUID],
      [IDL.Vec(ExternalBlob)],
      ['query'],
    ),
  'getDestinationWithGallery' : IDL.Func(
      [UUID],
      [TourDestination, IDL.Vec(ExternalBlob)],
      ['query'],
    ),
  'getFeaturedDestinations' : IDL.Func(
      [],
      [IDL.Vec(TourDestination)],
      ['query'],
    ),
  'getGalleryImages' : IDL.Func([UUID], [IDL.Vec(ExternalBlob)], ['query']),
  'getHomePageData' : IDL.Func(
      [],
      [
        IDL.Record({
          'agencies' : IDL.Vec(TourAgency),
          'popularHotels' : IDL.Vec(Hotel),
          'tourPackages' : IDL.Vec(TourPackage),
          'featuredDestinations' : IDL.Vec(TourDestination),
        }),
      ],
      ['query'],
    ),
  'getHotel' : IDL.Func([UUID], [Hotel], ['query']),
  'getTourPackage' : IDL.Func([UUID], [TourPackage], ['query']),
  'getUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleAgencyActive' : IDL.Func([UUID], [], []),
  'toggleDestinationActive' : IDL.Func([UUID], [], []),
  'toggleHotelActive' : IDL.Func([UUID], [], []),
  'togglePackageActive' : IDL.Func([UUID], [], []),
  'updateAgency' : IDL.Func([UUID, InputTourAgency], [], []),
  'updateBookingStatusAdmin' : IDL.Func([UUID, BookingStatus], [], []),
  'updateDestination' : IDL.Func([UUID, InputTourDestination], [], []),
  'updateHotel' : IDL.Func([UUID, InputHotel], [], []),
  'updateTourPackage' : IDL.Func([UUID, InputTourPackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UUID = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const InputTourAgency = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const PaymentMethod = IDL.Variant({
    'ovo' : IDL.Null,
    'linkAja' : IDL.Null,
    'dana' : IDL.Null,
    'gopay' : IDL.Null,
  });
  const InputBooking = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'destinationId' : IDL.Opt(UUID),
    'numGuests' : IDL.Nat,
    'totalPrice' : IDL.Float64,
    'customerEmail' : IDL.Text,
    'packageId' : IDL.Opt(UUID),
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const InputTourDestination = IDL.Record({
    'featured' : IDL.Bool,
    'directions' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'mainImage' : IDL.Opt(ExternalBlob),
    'coordinates' : Coordinates,
  });
  const InputHotel = IDL.Record({
    'pricePerNight' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'website' : IDL.Text,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const InputTourPackage = IDL.Record({
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'maxParticipants' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const TourAgency = IDL.Record({
    'id' : UUID,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const TourDestination = IDL.Record({
    'id' : UUID,
    'featured' : IDL.Bool,
    'active' : IDL.Bool,
    'directions' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'mainImage' : IDL.Opt(ExternalBlob),
    'location' : Coordinates,
  });
  const Hotel = IDL.Record({
    'id' : UUID,
    'active' : IDL.Bool,
    'pricePerNight' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'website' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const TourPackage = IDL.Record({
    'id' : UUID,
    'duration' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
    'maxParticipants' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Booking = IDL.Record({
    'id' : UUID,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'paymentMethod' : PaymentMethod,
    'bookedBy' : IDL.Principal,
    'customerPhone' : IDL.Text,
    'destinationId' : IDL.Opt(UUID),
    'createdAt' : Time,
    'numGuests' : IDL.Nat,
    'bookingDate' : Time,
    'totalPrice' : IDL.Float64,
    'customerEmail' : IDL.Text,
    'packageId' : IDL.Opt(UUID),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImages' : IDL.Func([UUID, IDL.Vec(ExternalBlob)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBookingClient' : IDL.Func([UUID], [], []),
    'checkBookingStatus' : IDL.Func([UUID], [BookingStatus], ['query']),
    'createAgency' : IDL.Func([InputTourAgency], [UUID], []),
    'createBooking' : IDL.Func([InputBooking], [UUID], []),
    'createDestination' : IDL.Func([InputTourDestination], [UUID], []),
    'createHotel' : IDL.Func([InputHotel], [UUID], []),
    'createTourPackage' : IDL.Func([InputTourPackage], [UUID], []),
    'deleteAgency' : IDL.Func([UUID], [], []),
    'deleteDestination' : IDL.Func([UUID], [], []),
    'deleteHotel' : IDL.Func([UUID], [], []),
    'deleteTourPackage' : IDL.Func([UUID], [], []),
    'getActiveAgencies' : IDL.Func([], [IDL.Vec(TourAgency)], ['query']),
    'getActiveDestinations' : IDL.Func(
        [],
        [IDL.Vec(TourDestination)],
        ['query'],
      ),
    'getActiveHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getActiveTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getAgency' : IDL.Func([UUID], [TourAgency], ['query']),
    'getAllAgencies' : IDL.Func([], [IDL.Vec(TourAgency)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllConfirmedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(TourDestination)], ['query']),
    'getAllFeaturedWithGallery' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TourDestination, IDL.Vec(ExternalBlob)))],
        ['query'],
      ),
    'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getBooking' : IDL.Func([UUID], [Booking], ['query']),
    'getBookingStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingBookings' : IDL.Nat,
            'activeHotels' : IDL.Nat,
            'activePackages' : IDL.Nat,
            'cancelledBookings' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'confirmedBookings' : IDL.Nat,
            'activeDestinations' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDestination' : IDL.Func([UUID], [TourDestination], ['query']),
    'getDestinationGalleryImages' : IDL.Func(
        [UUID],
        [IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'getDestinationWithGallery' : IDL.Func(
        [UUID],
        [TourDestination, IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'getFeaturedDestinations' : IDL.Func(
        [],
        [IDL.Vec(TourDestination)],
        ['query'],
      ),
    'getGalleryImages' : IDL.Func([UUID], [IDL.Vec(ExternalBlob)], ['query']),
    'getHomePageData' : IDL.Func(
        [],
        [
          IDL.Record({
            'agencies' : IDL.Vec(TourAgency),
            'popularHotels' : IDL.Vec(Hotel),
            'tourPackages' : IDL.Vec(TourPackage),
            'featuredDestinations' : IDL.Vec(TourDestination),
          }),
        ],
        ['query'],
      ),
    'getHotel' : IDL.Func([UUID], [Hotel], ['query']),
    'getTourPackage' : IDL.Func([UUID], [TourPackage], ['query']),
    'getUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleAgencyActive' : IDL.Func([UUID], [], []),
    'toggleDestinationActive' : IDL.Func([UUID], [], []),
    'toggleHotelActive' : IDL.Func([UUID], [], []),
    'togglePackageActive' : IDL.Func([UUID], [], []),
    'updateAgency' : IDL.Func([UUID, InputTourAgency], [], []),
    'updateBookingStatusAdmin' : IDL.Func([UUID, BookingStatus], [], []),
    'updateDestination' : IDL.Func([UUID, InputTourDestination], [], []),
    'updateHotel' : IDL.Func([UUID, InputHotel], [], []),
    'updateTourPackage' : IDL.Func([UUID, InputTourPackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };