/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TourDestination {
    id: UUID;
    featured: boolean;
    active: boolean;
    directions: string;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    address: string;
    category: string;
    rating: bigint;
    mainImage?: ExternalBlob;
    location: Coordinates;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TourAgency {
    id: UUID;
    active: boolean;
    name: string;
    createdAt: Time;
    description: string;
    email: string;
    updatedAt: Time;
    address: string;
    phone: string;
    services: Array<string>;
}
export interface InputTourPackage {
    duration: bigint;
    name: string;
    description: string;
    inclusions: Array<string>;
    maxParticipants: bigint;
    price: number;
}
export interface TourPackage {
    id: UUID;
    duration: bigint;
    active: boolean;
    name: string;
    createdAt: Time;
    description: string;
    inclusions: Array<string>;
    updatedAt: Time;
    maxParticipants: bigint;
    price: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface InputBooking {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    destinationId?: UUID;
    numGuests: bigint;
    totalPrice: number;
    customerEmail: string;
    packageId?: UUID;
}
export interface InputTourDestination {
    featured: boolean;
    directions: string;
    name: string;
    description: string;
    address: string;
    category: string;
    mainImage?: ExternalBlob;
    coordinates: Coordinates;
}
export interface InputHotel {
    pricePerNight: number;
    name: string;
    description: string;
    amenities: Array<string>;
    website: string;
    address: string;
    rating: bigint;
    phone: string;
}
export interface Hotel {
    id: UUID;
    active: boolean;
    pricePerNight: number;
    name: string;
    createdAt: Time;
    description: string;
    amenities: Array<string>;
    website: string;
    updatedAt: Time;
    address: string;
    rating: bigint;
    phone: string;
}
export type UUID = bigint;
export interface Booking {
    id: UUID;
    customerName: string;
    status: BookingStatus;
    paymentMethod: PaymentMethod;
    bookedBy: Principal;
    customerPhone: string;
    destinationId?: UUID;
    createdAt: Time;
    numGuests: bigint;
    bookingDate: Time;
    totalPrice: number;
    customerEmail: string;
    packageId?: UUID;
}
export interface InputTourAgency {
    name: string;
    description: string;
    email: string;
    address: string;
    phone: string;
    services: Array<string>;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    ovo = "ovo",
    linkAja = "linkAja",
    dana = "dana",
    gopay = "gopay"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    bootstrapAdmin(): Promise<void>;
    addGalleryImages(destinationId: UUID, newImages: Array<ExternalBlob>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBookingClient(bookingId: UUID): Promise<void>;
    checkBookingStatus(bookingId: UUID): Promise<BookingStatus>;
    createAgency(input: InputTourAgency): Promise<UUID>;
    createBooking(input: InputBooking): Promise<UUID>;
    createDestination(input: InputTourDestination): Promise<UUID>;
    createHotel(input: InputHotel): Promise<UUID>;
    createTourPackage(input: InputTourPackage): Promise<UUID>;
    deleteAgency(id: UUID): Promise<void>;
    deleteDestination(id: UUID): Promise<void>;
    deleteHotel(id: UUID): Promise<void>;
    deleteTourPackage(id: UUID): Promise<void>;
    getActiveAgencies(): Promise<Array<TourAgency>>;
    getActiveDestinations(): Promise<Array<TourDestination>>;
    getActiveHotels(): Promise<Array<Hotel>>;
    getActiveTourPackages(): Promise<Array<TourPackage>>;
    getAgency(id: UUID): Promise<TourAgency>;
    getAllAgencies(): Promise<Array<TourAgency>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllConfirmedBookings(): Promise<Array<Booking>>;
    getAllDestinations(): Promise<Array<TourDestination>>;
    getAllFeaturedWithGallery(): Promise<Array<[TourDestination, Array<ExternalBlob>]>>;
    getAllHotels(): Promise<Array<Hotel>>;
    getAllTourPackages(): Promise<Array<TourPackage>>;
    getBooking(bookingId: UUID): Promise<Booking>;
    getBookingStats(): Promise<{
        pendingBookings: bigint;
        activeHotels: bigint;
        activePackages: bigint;
        cancelledBookings: bigint;
        totalBookings: bigint;
        confirmedBookings: bigint;
        activeDestinations: bigint;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDestination(id: UUID): Promise<TourDestination>;
    getDestinationGalleryImages(destinationId: UUID): Promise<Array<ExternalBlob>>;
    getDestinationWithGallery(destinationId: UUID): Promise<[TourDestination, Array<ExternalBlob>]>;
    getFeaturedDestinations(): Promise<Array<TourDestination>>;
    getGalleryImages(destinationId: UUID): Promise<Array<ExternalBlob>>;
    getHomePageData(): Promise<{
        agencies: Array<TourAgency>;
        popularHotels: Array<Hotel>;
        tourPackages: Array<TourPackage>;
        featuredDestinations: Array<TourDestination>;
    }>;
    getHotel(id: UUID): Promise<Hotel>;
    getTourPackage(id: UUID): Promise<TourPackage>;
    getUserBookings(customerEmail: string): Promise<Array<Booking>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleAgencyActive(id: UUID): Promise<void>;
    toggleDestinationActive(id: UUID): Promise<void>;
    toggleHotelActive(id: UUID): Promise<void>;
    togglePackageActive(id: UUID): Promise<void>;
    updateAgency(id: UUID, input: InputTourAgency): Promise<void>;
    updateBookingStatusAdmin(bookingId: UUID, newStatus: BookingStatus): Promise<void>;
    updateDestination(id: UUID, input: InputTourDestination): Promise<void>;
    updateHotel(id: UUID, input: InputHotel): Promise<void>;
    updateTourPackage(id: UUID, input: InputTourPackage): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Coordinates as _Coordinates, ExternalBlob as _ExternalBlob, Hotel as _Hotel, InputBooking as _InputBooking, InputTourDestination as _InputTourDestination, PaymentMethod as _PaymentMethod, Time as _Time, TourAgency as _TourAgency, TourDestination as _TourDestination, TourPackage as _TourPackage, UUID as _UUID, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async bootstrapAdmin(): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.bootstrapAdmin();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.bootstrapAdmin();
        }
    }
    async addGalleryImages(arg0: UUID, arg1: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImages(arg0, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImages(arg0, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBookingClient(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBookingClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBookingClient(arg0);
            return result;
        }
    }
    async checkBookingStatus(arg0: UUID): Promise<BookingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkBookingStatus(arg0);
                return from_candid_BookingStatus_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkBookingStatus(arg0);
            return from_candid_BookingStatus_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAgency(arg0: InputTourAgency): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgency(arg0);
            return result;
        }
    }
    async createBooking(arg0: InputBooking): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_InputBooking_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_InputBooking_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDestination(arg0: InputTourDestination): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createDestination(await to_candid_InputTourDestination_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDestination(await to_candid_InputTourDestination_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createHotel(arg0: InputHotel): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHotel(arg0);
            return result;
        }
    }
    async createTourPackage(arg0: InputTourPackage): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createTourPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTourPackage(arg0);
            return result;
        }
    }
    async deleteAgency(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgency(arg0);
            return result;
        }
    }
    async deleteDestination(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDestination(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDestination(arg0);
            return result;
        }
    }
    async deleteHotel(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHotel(arg0);
            return result;
        }
    }
    async deleteTourPackage(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTourPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTourPackage(arg0);
            return result;
        }
    }
    async getActiveAgencies(): Promise<Array<TourAgency>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAgencies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAgencies();
            return result;
        }
    }
    async getActiveDestinations(): Promise<Array<TourDestination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDestinations();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDestinations();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveHotels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveHotels();
            return result;
        }
    }
    async getActiveTourPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTourPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTourPackages();
            return result;
        }
    }
    async getAgency(arg0: UUID): Promise<TourAgency> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgency(arg0);
            return result;
        }
    }
    async getAllAgencies(): Promise<Array<TourAgency>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgencies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgencies();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllConfirmedBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConfirmedBookings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConfirmedBookings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDestinations(): Promise<Array<TourDestination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDestinations();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDestinations();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeaturedWithGallery(): Promise<Array<[TourDestination, Array<ExternalBlob>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeaturedWithGallery();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeaturedWithGallery();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHotels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHotels();
            return result;
        }
    }
    async getAllTourPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTourPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTourPackages();
            return result;
        }
    }
    async getBooking(arg0: UUID): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingStats(): Promise<{
        pendingBookings: bigint;
        activeHotels: bigint;
        activePackages: bigint;
        cancelledBookings: bigint;
        totalBookings: bigint;
        confirmedBookings: bigint;
        activeDestinations: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStats();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDestination(arg0: UUID): Promise<TourDestination> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestination(arg0);
                return from_candid_TourDestination_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestination(arg0);
            return from_candid_TourDestination_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDestinationGalleryImages(arg0: UUID): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinationGalleryImages(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinationGalleryImages(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDestinationWithGallery(arg0: UUID): Promise<[TourDestination, Array<ExternalBlob>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinationWithGallery(arg0);
                return [
                    from_candid_TourDestination_n21(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n33(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinationWithGallery(arg0);
            return [
                from_candid_TourDestination_n21(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n33(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getFeaturedDestinations(): Promise<Array<TourDestination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedDestinations();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedDestinations();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImages(arg0: UUID): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomePageData(): Promise<{
        agencies: Array<TourAgency>;
        popularHotels: Array<Hotel>;
        tourPackages: Array<TourPackage>;
        featuredDestinations: Array<TourDestination>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomePageData();
                return from_candid_record_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomePageData();
            return from_candid_record_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotel(arg0: UUID): Promise<Hotel> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotel(arg0);
            return result;
        }
    }
    async getTourPackage(arg0: UUID): Promise<TourPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.getTourPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTourPackage(arg0);
            return result;
        }
    }
    async getUserBookings(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleAgencyActive(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAgencyActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAgencyActive(arg0);
            return result;
        }
    }
    async toggleDestinationActive(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDestinationActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDestinationActive(arg0);
            return result;
        }
    }
    async toggleHotelActive(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHotelActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHotelActive(arg0);
            return result;
        }
    }
    async togglePackageActive(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePackageActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePackageActive(arg0);
            return result;
        }
    }
    async updateAgency(arg0: UUID, arg1: InputTourAgency): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgency(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgency(arg0, arg1);
            return result;
        }
    }
    async updateBookingStatusAdmin(arg0: UUID, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatusAdmin(arg0, to_candid_BookingStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatusAdmin(arg0, to_candid_BookingStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDestination(arg0: UUID, arg1: InputTourDestination): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDestination(arg0, await to_candid_InputTourDestination_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDestination(arg0, await to_candid_InputTourDestination_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHotel(arg0: UUID, arg1: InputHotel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotel(arg0, arg1);
            return result;
        }
    }
    async updateTourPackage(arg0: UUID, arg1: InputTourPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTourPackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTourPackage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_TourDestination_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourDestination): Promise<TourDestination> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UUID]): UUID | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UUID;
    featured: boolean;
    active: boolean;
    directions: string;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    address: string;
    category: string;
    rating: bigint;
    mainImage: [] | [_ExternalBlob];
    location: _Coordinates;
}): Promise<{
    id: UUID;
    featured: boolean;
    active: boolean;
    directions: string;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    address: string;
    category: string;
    rating: bigint;
    mainImage?: ExternalBlob;
    location: Coordinates;
}> {
    return {
        id: value.id,
        featured: value.featured,
        active: value.active,
        directions: value.directions,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        address: value.address,
        category: value.category,
        rating: value.rating,
        mainImage: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.mainImage)),
        location: value.location
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UUID;
    customerName: string;
    status: _BookingStatus;
    paymentMethod: _PaymentMethod;
    bookedBy: Principal;
    customerPhone: string;
    destinationId: [] | [_UUID];
    createdAt: _Time;
    numGuests: bigint;
    bookingDate: _Time;
    totalPrice: number;
    customerEmail: string;
    packageId: [] | [_UUID];
}): {
    id: UUID;
    customerName: string;
    status: BookingStatus;
    paymentMethod: PaymentMethod;
    bookedBy: Principal;
    customerPhone: string;
    destinationId?: UUID;
    createdAt: Time;
    numGuests: bigint;
    bookingDate: Time;
    totalPrice: number;
    customerEmail: string;
    packageId?: UUID;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n12(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n28(_uploadFile, _downloadFile, value.paymentMethod),
        bookedBy: value.bookedBy,
        customerPhone: value.customerPhone,
        destinationId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.destinationId)),
        createdAt: value.createdAt,
        numGuests: value.numGuests,
        bookingDate: value.bookingDate,
        totalPrice: value.totalPrice,
        customerEmail: value.customerEmail,
        packageId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.packageId))
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    agencies: Array<_TourAgency>;
    popularHotels: Array<_Hotel>;
    tourPackages: Array<_TourPackage>;
    featuredDestinations: Array<_TourDestination>;
}): Promise<{
    agencies: Array<TourAgency>;
    popularHotels: Array<Hotel>;
    tourPackages: Array<TourPackage>;
    featuredDestinations: Array<TourDestination>;
}> {
    return {
        agencies: value.agencies,
        popularHotels: value.popularHotels,
        tourPackages: value.tourPackages,
        featuredDestinations: await from_candid_vec_n20(_uploadFile, _downloadFile, value.featuredDestinations)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_TourDestination, Array<_ExternalBlob>]): Promise<[TourDestination, Array<ExternalBlob>]> {
    return [
        await from_candid_TourDestination_n21(_uploadFile, _downloadFile, value[0]),
        await from_candid_vec_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ovo: null;
} | {
    linkAja: null;
} | {
    dana: null;
} | {
    gopay: null;
}): PaymentMethod {
    return "ovo" in value ? PaymentMethod.ovo : "linkAja" in value ? PaymentMethod.linkAja : "dana" in value ? PaymentMethod.dana : "gopay" in value ? PaymentMethod.gopay : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TourDestination>): Promise<Array<TourDestination>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TourDestination_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_TourDestination, Array<_ExternalBlob>]>): Promise<Array<[TourDestination, Array<ExternalBlob>]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
function to_candid_BookingStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InputBooking_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InputBooking): _InputBooking {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_InputTourDestination_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InputTourDestination): Promise<_InputTourDestination> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    destinationId?: UUID;
    numGuests: bigint;
    totalPrice: number;
    customerEmail: string;
    packageId?: UUID;
}): {
    customerName: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    destinationId: [] | [_UUID];
    numGuests: bigint;
    totalPrice: number;
    customerEmail: string;
    packageId: [] | [_UUID];
} {
    return {
        customerName: value.customerName,
        paymentMethod: to_candid_PaymentMethod_n16(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        destinationId: value.destinationId ? candid_some(value.destinationId) : candid_none(),
        numGuests: value.numGuests,
        totalPrice: value.totalPrice,
        customerEmail: value.customerEmail,
        packageId: value.packageId ? candid_some(value.packageId) : candid_none()
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured: boolean;
    directions: string;
    name: string;
    description: string;
    address: string;
    category: string;
    mainImage?: ExternalBlob;
    coordinates: Coordinates;
}): Promise<{
    featured: boolean;
    directions: string;
    name: string;
    description: string;
    address: string;
    category: string;
    mainImage: [] | [_ExternalBlob];
    coordinates: _Coordinates;
}> {
    return {
        featured: value.featured,
        directions: value.directions,
        name: value.name,
        description: value.description,
        address: value.address,
        category: value.category,
        mainImage: value.mainImage ? candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.mainImage)) : candid_none(),
        coordinates: value.coordinates
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    ovo: null;
} | {
    linkAja: null;
} | {
    dana: null;
} | {
    gopay: null;
} {
    return value == PaymentMethod.ovo ? {
        ovo: null
    } : value == PaymentMethod.linkAja ? {
        linkAja: null
    } : value == PaymentMethod.dana ? {
        dana: null
    } : value == PaymentMethod.gopay ? {
        gopay: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
async function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
